[package]
name = "io_aeron_archive_codecs_mark"
version = "0.1.0"
authors = ["sbetool"]
description = "Codecs for Mark file of Aeron Archive."
edition = "2018"

[lib]
name = "io_aeron_archive_codecs_mark"
path = "src/lib.rs"
