[package]
name = "io_aeron_archive_codecs"
version = "0.1.0"
authors = ["sbetool"]
description = "Message Codecs for communicating with an Aeron Archive."
edition = "2018"

[lib]
name = "io_aeron_archive_codecs"
path = "src/lib.rs"
